#ifndef PYSCHEDULE_MACROS_H_
#define PYSCHEDULE_MACROS_H_

#define CLIENT_ID ID_BASE
#define SERVER_ID (CLIENT_ID + 1)

#define CLIENT_PORT GET_PORT(CLIENT_ID)
#define SERVER_PORT GET_PORT(SERVER_ID)

#endif //PYSCHEDULE_MACROS_H_

