#ifndef PYSCHEDULE_MACROS_H_
#define PYSCHEDULE_MACROS_H_

#define CLIENT_ID ID_BASE
#define SERVER_ID (CLIENT_ID + 1)

#define CLIENT_PORT (PORT_BASE + CLIENT_ID)
#define SERVER_PORT (PORT_BASE + SERVER_ID)

#endif //PYSCHEDULE_MACROS_H_

