#ifndef PYSCHEDULE_MACROS_H_
#define PYSCHEDULE_MACROS_H_

#define PNODE_NUM 1
#define HOST_NUM 4
#define USER_NUM 16

#define PORT_BASE 20000

#define HOST "127.0.0.1"

#define MESSAGE_SIZE_MAX 128

#define THREAD_NUM 4

#endif //PYSCHEDULE_MACROS_H_

