#ifndef PYSCHEDULE_MACROS_H_
#define PYSCHEDULE_MACROS_H_

#define PNODE_NUM 1
#define GATE_NUM 4
#define USER_NUM 16

#define PORT_BASE 20000
#define ID_BASE 1

#define PNODE_ID_START ID_BASE
#define PNODE_ID_END (PNODE_ID_START + PNODE_NUM)
#define GATE_ID_START PNODE_ID_END
#define GATE_ID_END (GATE_ID_START + GATE_NUM)
#define USER_ID_START GATE_ID_END
#define USER_ID_END (USER_ID_START + USER_NUM)

#define LOCALHOST "127.0.0.1"

#define MESSAGE_SIZE_MAX 128

#define THREAD_NUM 4

#endif //PYSCHEDULE_MACROS_H_

