#ifndef PYSCHEDULE_MACROS_H_
#define PYSCHEDULE_MACROS_H_

#define CLIENT_NUM 20
#define SERVER_NUM 1

#define CLIENT_ID_START ID_BASE
#define CLIENT_ID_END (CLIENT_ID_START + CLIENT_NUM)
#define SERVER_ID CLIENT_ID_END

#define GET_PORT(NODE_ID) (NODE_ID + PORT_BASE)

#endif //PYSCHEDULE_MACROS_H_

